config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'inquiry/new'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  root to: "top#index"
  resources :blogs
  get 'inquiry', to: 'inquiry#new'
  post 'inquiry/confirm', to: 'inquiry#confirm'
  post 'inquiry/thanks', to: 'inquiry#thanks'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  validates :name, presence: {message: '名前を入力してください'}
  validates :email, presence: {message: 'メールアドレスを入力してください'}
  validates :message, presence: {message: 'お問い合わせ内容を入力してください'}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  
  before_filter :authenticate_user! 

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
    else
    render action: 'new'
    end
  end

  def thanks
    @inquiry = Inquiry.create(inquiry_params)
  end

  private
    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :message)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/inquiry/confirm.html.erb
<div class="page-header">
  <h1>お問い合わせ（内容の確認）</h1>
</div>

<%= form_for @inquiry, url: inquiry_thanks_path do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@inquiry.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '確認', class: 'btn btn-primary' %>
<% end %>

app/views/inquiry/new.html.erb
<%= form_for @inquiry, url: inquiry_confirm_path do |f| %>
  <div class="page-header">
    <h1>お問い合わせ</h1>
    <p>すべての入力欄にご入力ください</p>
  </div>

  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> 入力された内容にエラーがあります。</h2>
      <ul>
      <% @inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table">
    <tr>
      <th>名前<span class="text-danger"></span></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th>メールアドレス<span class="text-danger"></span></th>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td><%= f.text_area :message %></td>
    </tr>
  </table>
  <%= f.submit '確認', class: 'btn btn-primary' %>
<% end %>

app/views/inquiry/thanks.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせいただき、ありがとうございました。
</p>
<%= link_to "戻る", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja" >
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<meta charset="UTF-8">
<head>
  <title>Dive into Code</title>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p> 
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<div class="boxA">
  <div class="box1">
    <div class="site">
      <h1><a href="#">Dive into Code by KO MACHIDA</a></h1>
     </div>
  </div>

  <div class="box2">
    <nav class="menu">
      <ul>
        <li><%= link_to "トップ", root_path %></li>
        <li><%= link_to "お問い合わせ", inquiry_path %></li>
        <% if user_signed_in? %> 
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li> 
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li> 
        <% end %>
      </ul>
    </nav>
  </div>
</div>

<div class="box3">
  <%= image_tag("header.png", class: "topimg") %>
</div>

<div class="box4">
  <div class="box4-1">
    <div class="merit">
      <a href="#">
        <i class="fa fa-heart"></i>
        <h1>経験ゼロの初心者向け</h1>
        <p>全10回講座の課題解決型プログラム。経験ゼロからWebエンジニアになっていただきます。</p>
      </a>
    </div>
  </div>
  <div class="box4-2">
    <div class="merit">
      <a href="#">
        <i class="fa fa-television"></i>
        <h1>オンラインサポート付き</h1>
        <p>専用のfacebookグループ内やNitrousのコラボレーション機能を経由して随時オンラインサポート</p>
      </a>
    </div>
  </div>
  <div class="box4-3">
    <div class="merit">
      <a href="#">
        <i class="fa fa-connectdevelop"></i>
        <h1>チームで実践「受託開発」</h1>
        <p>ひとりではなく開発チームを結成し、実ビジネスの受託開発を経験して卒業していただきます。</p>
      </a>
    </div>
  </div>
</div>

<div class="box5">
  <div class="copyright">
    <p>Copyright &copy; 2015 Dive into Code All Rights Reserved.</p>
  </div>
</div>